from dbinit import Session, User
import hashlib


def _hash_password(password: str) -> str:
    """Deterministic SHA-256 hashing for passwords."""
    return hashlib.sha256(password.encode("utf-8")).hexdigest()

# CREATE: Add a new user
def create_user(username, password, score):
    with Session() as session:
        new_user = User(username=username, password=_hash_password(password), score=score)
        session.add(new_user)
        session.commit()
        session.refresh(new_user) # Gives you the ID generated by the DB
        return new_user

# READ ALL: Get everything in the table
def read_all_users():
    with Session() as session:
        users = session.query(User).all()
        for user in users:
            user.password = None  # Hide passwords before returning
        return users

# READ: Get one user by ID
def read_user_by_id(user_id):
    with Session() as session:
        return session.query(User).filter_by(id=user_id).first()

# UPDATE: Change an existing record
def update_user_score(user_id, new_score):
    with Session() as session:
        user = session.query(User).filter_by(id=user_id).first()
        if user and new_score > user.score:  # Only update if the new score is higher
            user.score = new_score
            session.commit()
            return True
        return False

# DELETE: Remove a record
def delete_user(user_id):
    with Session() as session:
        user = session.query(User).filter_by(id=user_id).first()
        if user:
            session.delete(user)
            session.commit()
            return True
        return False
    
def check_user_password(username, password):
    with Session() as session:
        print(f"Checking password for user: {username}")
        print(f"Provided password: {password}")
        print(f"Hashed provided password: {_hash_password(password)}")
        user = session.query(User).filter_by(username=username).first()
        if user and user.password == _hash_password(password):
            return user.id
        return False

