from dbinit import Session, User

# CREATE: Add a new user
def create_user(username, password, score):
    with Session() as session:
        new_user = User(username=username, password=password, score=score)
        session.add(new_user)
        session.commit()
        session.refresh(new_user) # Gives you the ID generated by the DB
        return new_user

# READ ALL: Get everything in the table
def read_all_users():
    with Session() as session:
        return session.query(User).all()

# READ: Get one user by ID
def read_user_by_id(user_id):
    with Session() as session:
        return session.query(User).filter_by(id=user_id).first()

# UPDATE: Change an existing record
def update_user_score(user_id, new_score):
    with Session() as session:
        user = session.query(User).filter_by(id=user_id).first()
        if user:
            user.score = new_score
            session.commit()
            return True
        return False

# DELETE: Remove a record
def delete_user(user_id):
    with Session() as session:
        user = session.query(User).filter_by(id=user_id).first()
        if user:
            session.delete(user)
            session.commit()
            return True
        return False
    
def check_user_password(username, password):
    with Session() as session:
        user = session.query(User).filter_by(username=username).first()
        if user and user.password == password:
            return True
        return False

